# Generated by Django 2.2 on 2021-11-20 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Название категории')),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название вещи')),
                ('price', models.PositiveIntegerField(null=True, verbose_name='Цена')),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='Фотография')),
                ('garment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Categories')),
            ],
            options={
                'verbose_name': 'элемент одежды',
                'verbose_name_plural': 'Одежда',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины пользователей',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Profile_Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ManyToManyField(blank=True, to='Site.Clothes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Site.Profile')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['id'],
            },
        ),
    ]
