# Generated by Django 2.2 on 2021-11-20 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_cart',
            name='item',
        ),
        migrations.AddField(
            model_name='profile_cart',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Clothes'),
        ),
    ]
