# Generated by Django 2.2 on 2021-11-20 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_auto_20211120_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_cart',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Clothes', unique=True),
        ),
    ]
