# Generated by Django 2.2 on 2021-12-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Заказы пользователей'},
        ),
        migrations.AddField(
            model_name='orders',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('NR', 'Не готов'), ('R', 'Готов')], default='NR', max_length=2, verbose_name='Статус заказа'),
        ),
    ]
