# Generated by Django 2.2 on 2021-12-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_auto_20211205_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
