# Generated by Django 2.2 on 2021-12-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0009_auto_20211205_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('profile_cart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Site.Profile_Cart')),
            ],
            bases=('Site.profile_cart',),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
