# Generated by Django 2.2 on 2021-12-07 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0012_auto_20211205_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_in_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Clothes', unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Orders'),
        ),
    ]
