# Generated by Django 2.2 on 2021-12-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0014_auto_20211207_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ManyToManyField(to='Site.Profile', verbose_name='Покупатель'),
        ),
    ]
