# Generated by Django 2.2 on 2021-12-07 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0019_auto_20211207_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Site.Profile'),
        ),
    ]
