# Generated by Django 2.2 on 2021-12-07 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0021_auto_20211207_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='item_in_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Clothes'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
