# Generated by Django 2.2 on 2021-12-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0022_auto_20211207_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='item_in_order',
        ),
        migrations.AddField(
            model_name='orders',
            name='item_in_order',
            field=models.ManyToManyField(to='Site.Clothes'),
        ),
    ]
