# Generated by Django 2.2 on 2021-12-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0023_auto_20211207_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='item_in_order',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.Clothes')),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Site.Orders')),
            ],
        ),
    ]
