# Generated by Django 2.2 on 2021-12-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0035_auto_20211207_2121'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('order_id', 'item')},
        ),
    ]
