# Generated by Django 2.2 on 2021-12-08 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0038_auto_20211207_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.Profile'),
        ),
    ]
