# Generated by Django 2.2 on 2021-12-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0039_auto_20211208_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('NR', 'Формируется'), ('R', 'Готов')], default='NR', max_length=2, verbose_name='Статус заказа'),
        ),
    ]
