# Generated by Django 2.2 on 2021-12-11 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0040_auto_20211208_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='data_field',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
