# Generated by Django 2.2 on 2021-12-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0043_orders_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_price',
            field=models.IntegerField(editable=False),
        ),
    ]
