# Generated by Django 2.2 on 2021-12-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0044_auto_20211211_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_price',
            field=models.IntegerField(editable=False, verbose_name='Сумма заказа'),
        ),
    ]
